### PR TITLE
Services refactoring

### LINKED ISSUE #53: I've got 500 response for real pipeline_hook tasks
OK, I've got 500 response for real pipeline tasks. I don't see result green symbols on GITLAB tab. Look further to find out more details.

Request data: https://gist.github.com/foxweb/c7c287a3272583f53a07541b281e5c11

image

Request data: https://gist.github.com/foxweb/c7c287a3272583f53a07541b281e5c11
```

D, [2023-11-28T01:19:32.194672 #7975] DEBUG -- : Received gitlab webhook pipeline_hook
E, [2023-11-28T01:19:32.195405 #7975] ERROR -- : Failed to handle pipeline_hook from Gitlab: undefined method `iid?' for nil:NilClass undefined method `iid?' for nil:NilClass
D, [2023-11-28T01:19:32.209328 #7975] DEBUG -- :   ActiveRecord::SchemaMigration Pluck (1.5ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
E, [2023-11-28T01:19:32.211345 #7975] ERROR -- : user=29 undefined method `iid?' for nil:NilClass: undefined method `iid?' for nil:NilClass
D, [2023-11-28T01:19:32.211416 #7975] DEBUG -- : [NoMethodError] undefined method `iid?' for nil:NilClass: modules/gitlab_integration/lib/open_project/gitlab_integration/notification_handler/pipeline_hook.rb:56:in `associated_with_mr?'; modules/gitlab_integration/lib/open_project/gitlab_integration/notification_handler/pipeline_hook.rb:40:in `process'; modules/gitlab_integration/lib/open_project/gitlab_integration/notification_handlers.rb:68:in `block in pipeline_hook'; modules/gitlab_integration/lib/open_project/gitlab_integration/notification_handlers.rb:75:in `with_logging'; modules/gitlab_integration/lib/open_project/gitlab_integration/notification_handlers.rb:67:in `pipeline_hook'; lib_static/open_project/notifications.rb:57:in `block in subscribe'; lib_static/open_project/notifications.rb:81:in `send'; modules/gitlab_integration/lib/open_project/gitlab_integration/hook_handler.rb:60:in `process'; modules/gitlab_integration/lib/open_project/gitlab_integration/engine.rb:55:in `block (2 levels) in <class:Engine>'; modules/webhooks/lib/open_project/webhooks/hook.rb:44:in `handle'; modules/webhooks/app/controllers/webhooks/incoming/hooks_controller.rb:56:in `handle_hook'
```

_Originally posted by @foxweb in https://github.com/btey/openproject-gitlab-integration/issues/43#issuecomment-1828634917_

### PR DESCRIPTION
**Pull request by foxweb**
Introducing ParamsHelper.

Not tested yet.

Closes #53

### CODE REVIEW

**Comment by btey** [comment]
Hi @foxweb 

Let me know if your PR is ready or you expect more changes.

Thanks.

**Comment by foxweb** [comment]
@btey I've just added more changes for 13.1.1, I need more time for testing.
Your last updates for 13.1 is OK. I have already upgraded to 13.1.1, saw the permission issues and fixed them in my OP repository. Thank you for your support!

**Comment by foxweb** [comment]
Hello @btey
This PR successfully tested on production and ready to merge.

**Comment by btey** [comment]
Hi @foxweb 

Thank you so much for your work! Could you just change the version from v2.1.5 to v2.1.6. A few weeks ago another developer made a contribution that increased the version to v2.1.5.

Thanks a lot!
Ben

**Comment by btey** [comment]
Hi @foxweb 

I already changed the version.

Thank you for your work!
Ben

**Pull request merged**
